# Electrical Concepts

This class and modern life relies heavily on electricity and electronics.  Our course electronics text points this out quite eloquently:

<p><i>The history of electricity starts more than two thousand years ago, with the Greek philosopher Thales being the earliest known researcher into electricity. But it was Alessandro Volta who created the most common DC power source, the battery (for this invention the unit Volt was named after him).</p>
<p>Direct current (also known as DC) is the flow of charged particles in one unchanging direction (most commonly found as electron flow through conductive materials). DC can be found in just about every home and electronic device, as it is more practical (compared to AC from power stations) for many consumer devices. Just a few of the places where you can find direct current are batteries, phones, computers, cars, TVs, calculators, and even lightning.</i></p>
<p>We will begin exploring a number of concepts relating to electricity as we will essentially be using electrons as our modes of information processing.  From the electrons that flow through a button or distance sensor to be read by the microprocessor to those which supply the power for our motors and servos, we are heavily dependent on electricity.  Before we get into this, we need to go over some very important concepts.  Take out your Raspberry Pi and follow along with the video below.</p>

Video here
<br>
<br>
<b>Rules of this course in regards to electricity:</b>
<ol><li>Always work only with DC electricity, never use AC voltage except for when you plug your Raspberry Pi into the outlet.</li>
<li>Always work on your circuits when the devices are unplugged and batteries removed.  Not only is this a safety issue, it will prevent the need to replace electrical components</li>
<li>Only use the components listed in the laboratory activity on which you are working.  Do not try new components you have never used before or are unfamiliar with.</li>
<li>Keep your work area clean and uncluttered.  Do not keep beverages on your workstation.</li>
</ol>

Circuit lab setup

## Circuits

A basic understanding of circuit electricity is essential going forward.  For this section of the course, we will begin using our online textbook.  It gives us an excellent overview of electrons, circuits and polarity.  Please keep in mind that, in order to begin using the Raspberry Pi (i.e. receiving the power supply) you will need to pass all of the required quizzes with at least a 70%.

<b>Key Concepts of Section 3.1</b>

<ul>
  <li>A circuit is a loop of conductive material.</li>
  <li>In order for electrons to flow a <i>closed circuit</i> is required.</li>
  <li>A circuit is <i>open</i> or <i>broken</i> if a complete path for the electrons to flow no longer exists.</li>
</ul>  

Rather than me trying to do a better job than our textbook, you are going to read the <a href="https://www.allaboutcircuits.com/textbook/direct-current/chpt-1/electric-circuits/" target="_blank">short section on circuits</a>.  These questions will be similar to those that you will see on your unit exam (The one you need at least a 70% on to move on).  So...that means that you are not completing this worksheet for a grade.  Instead, you are trying to measure how well you learned the concepts in the reading.  Much of this year's content will be delivered this way.  Get your head around the idea of learning for the sake of learning.

To help you understand this concept, here is an excellent video from SparkFun Electronics on the topic.

<iframe width="420" height="315"
src="https://www.youtube.com/embed/kYwNj9uauJ4">
</iframe>
<br>
<u>Assignments for section 3.1</u>: 
<ol>
  <li>After reading the section on circuits, complete the <a href="https://www.allaboutcircuits.com/worksheets/elementary-circuits/online" target="_blank">worksheet</a></li>
  <li>Using (tool for this), design a closed circuit with the following components:</li>
    <ul>
      <li>5V DC power supply</li>
      <li>Red LED</li>
      <li>330 Ohm resistor</li>
    </ul>
</ol>    
Submit the (method of submission) here.

## Voltage and Current

The movement of electrons from one pole to another is what we use in robotics to make our robots work.  By altering the volume of electrons moving through the wires connected to a motor we can alter the speed of the wheel attached to the motor.  The potential energy coming in to our microprocessor pin over a wire attached to a photoresistor tells us the level of brightness or lumosity in a room.  Putting these two concepts together we could create a robotic system that opens the blinds on our lab when the sun sets in the west.  That is, of course, if we can program our system to make that decision on its own.  We will get to the programming part later.  For now, we will examine the concepts of voltage and current which allow us, along with resistance, to receive information through sensor and send information out to an actuation device like a motor.



## Resistance

## Ohm's Law

## Using a Digital Multimeter

This section will become active in the event that we are not using remote instruction.

## Basic Soldering

This section will become active in the event that we are not using remote instruction.
