# Robotic Types

A fundamental qustion in mechatronics is, "what is a robot?"  Over the course of this year, you should be able to come up with some answers for this question.  This short section is aimed at helping us understand that before moving on to our final project.  Now that you have learned basics of electronics, mechanics and programming, you may begin to explore the larger field of robotics applications.  For this assignment we will begin with background from some experts to supplement what you have already learned.

To begin, let's take a look at some of the most recent robotics development using a very thorough BBC documentary:

<iframe width="420" height="315"
src="https://www.youtube.com/embed/hRuBZLe8vfs">
</iframe>
<br>

Make a list of your own criteria that make something a robot.  This list may include anything you like.  Give a justification for each criteria.

Read <a href="https://robots.ieee.org/learn/what-is-a-robot/#" targe ="_blank">this page</a> from the IEEE which attempts to help us decide what a robot is and is not.  How does this change your list?  Be sure to listen to the speakers on the page.

<b>Assignment 6.0</b><br>
Choose one of the robot types from <a href="https://robots.ieee.org/learn/types-of-robots/" target ="_blank">this page</a>.  Conduct your own reaserch and create a 5-10 minute presentation demonstrating the characteristics and applications of your chosen robot type.  Provide video descriptions of these real-world robots as well as the educational pathways needed to work with these robot types.