# Going Further with Robotics

## Robotics in Higher Education

You are taking this course because you are interested in learning about robots, obviously.  You may want to pursue this subject after you leave high school as well.  What does it mean to be a robotic engineer or roboticist?  This is more than having an enthusiasm for the field.  It means pursuing an educational path that prepares you for a profession in robotics.  It also looks different depending on what you want to do with robotics.  Robotics engineering is a standalone field within mechatronics.  However, many fields benefit from this area of study even if it not the primare goal.  One of our recent alumns, Katie Schutt, summs up her path through robotics at Windsor High School and how it helped her get to Aeronautical Engineering:

>WHS robotics was the high school program that probably best prepared me for life and education in college, especially as an incoming engineering student. I learned technical skills around designing and testing under the pressure of requirements and a deadline, and the necessary programming logic and proficiency. Equally important, I developed skills in public speaking, documenting the proposals and then progress of my projects, and the ability to constructively work with a team. All of these skills were heavily emphasized and required to succeed in my first semester at CU, and robotics provided the foundation for those skills to be built upon. 

Katie is working to become an astronaut with the goal of traveling to other planets in our solar system.  The technical skills she is building will give her opportunities like this.  It began in her robotics classroom at WHS.

You may not know where you want to take robotics yet.  There are hundred of <a href="https://en.wikipedia.org/wiki/Outline_of_robotics#Branches_of_robotics" target ="_blank">branches of robotics</a>.  All of them have some common threads.  In high school some of these skills may be learned to prepare students for university level robotics:
<ul>
  <li>Math</li>
    <ul>
      <li>Algebra</li>
      <li>Geometry</li>
      <li>Trigonometry</li>
      <li>Calculus</li>
    </ul>  
  <li>Physics</li>
    <ul>
      <li>Dynamics</li>
      <li>Kinematics</li>
    </ul>
  <li>Computer Science</li>
    <ul>
      <li>Programming languages</li>
      <li>Computation logic</li>
      <li>Cloud Computing</li>
    </ul>
  <li>Engineering</li>
  <li>Language Arts</li>
</ul>

To get on this path be sure to talk to your counselor about your goals.  Feel free to ask me about this as well.  We have many former students who have pursued this field and are attending colleges all over the United States.  An excellent way to learn more is to attend an engineering day at <a href="https://www.engr.colostate.edu/future-students/engineering-exploration-day/" target ="_blank">Colorado State University</a> or <a href="https://www.colorado.edu/engineering/admissions/visit-us#block-bean-block-section-prospective-even-0" target ="_blank">the University of Colorado in Boulder</a>.  Most high school students find that a visit to campus makes the potential college experience more attainable and realistic.

## Supplemental Videos

<caption><h3>The Genius of George Boole</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/Hljir_TyTEw">
</iframe>
<br>

<caption><h3>Shakey:Experiments in Robotic Planning and Learning (1972)</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/GmU7SimFkpU">
</iframe>
<br>

<caption><h3>BBC Documentary - Hyper Evolution : Rise Of The Robots (Part 1)</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/hRuBZLe8vfs">
</iframe>
<br>

<caption><h3>BBC Documentary - Hyper Evolution : Rise Of The Robots (Part 2)</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/9SA2WLDB65A">
</iframe>
<br>

<caption><h3>BBC Documentary - Hyper Evolution : Rise Of The Robots (Part 3)</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/D22UOL-ncgw">
</iframe>
<br>

<caption><h3>Robots that fly ... and cooperate | Vijay Kumar</h3></caption>
<iframe width="420" height="315"
src="https://www.youtube.com/embed/4ErEBkj_3PY">
</iframe>
<br>