--- 
title: "Robotics Engineering"
author: "Steve Cline"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "During your particpation in the Robotics Engineering Course here at Windsor High School, you will use this online book as a guide through the content."
---

# Prerequisites

<p><b><i>While we will use Canvas as much as possible in this course, it is not a suitable platform for a course which relies heavily on programming.  As a result, you will need to become familiar with using sites like GitHub.  Familiarity with these sites will prepare you for future work in college and beyond.</b></i></p>

For this course you will need to do the following to prepare to learn:

<ol>
  <li>Locate the [Course Lecture Notes] section of this site.  Browse through the notes to gain an understanding of what we will be covering this year.</li>
  <li>Sign up for a GitHub account and fill out this form.</li>
  <li>Bookmark the course <a href="https://github.com/stcline/Robotics_Engineering_Course" target="_blank">GitHub Repository</a>.  This is where many of the programming resources will be found.  In addition, assignments will be submitted here.</li>
  <li>Find the <a href="https://greenteapress.com/wp/think-python-2e/" target="_blank"> Python textbook</a> for the course. <i>While this course includes more than just programming, we will dedicate quite a bit of time to learning Python</i>.</li>
  <li>Subscribe to the course <a href="https://www.youtube.com/playlist?list=PLdzkJRGG1oi3xGaaHM44BkpW-bYuD9KQS" target="_blank">YouTube Channel</a>.</li>  Directions for how to do this are found in the [Follow the Course YouTube Channel] section of this site.</li>
  <li>Log on to the class Jupyter Notebook server</li>
  <li>Sign up for an OnShape account by following the instructions in the [OnShape Account Setup] section of this site.</li>
  <li>Complete the WHS Mechatronics Lab Code of Conduct Agreement.</li>
